/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 01-Oct-2025 4:11:44 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Prestamo_Prestamo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Prestamo] DROP CONSTRAINT [FK_Prestamo_Prestamo]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Prestamo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Prestamo]
GO

/* Create Tables */

CREATE TABLE [Prestamo]
(
	[num] NOT NULL,
	[monto] NOT NULL,
	[fecha] NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Prestamo] 
 ADD CONSTRAINT [PK_Prestamo]
	PRIMARY KEY CLUSTERED ([num] ASC,[monto] ASC,[fecha] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Prestamo] ADD CONSTRAINT [FK_Prestamo_Prestamo]
	FOREIGN KEY ([num],[monto],[fecha]) REFERENCES [Prestamo] ([num],[monto],[fecha]) ON DELETE No Action ON UPDATE No Action
GO
